/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamenim.view;
import gamenim.model.CustomJButton;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author iqbal
 */
public class BoardView extends javax.swing.JFrame {

    ArrayList<CustomJButton> stickButton = new ArrayList<>();
    
    //setter & getter
    public void setStickButton(ArrayList<CustomJButton> stickButton) {this.stickButton = stickButton; }
    public ArrayList<CustomJButton> getStickButton(){ return stickButton;}
    //end of setter & getter
    //myFunction
    public CustomJButton createNewButton(String text, int index) {
        CustomJButton newButton = new CustomJButton(index);
        newButton.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 48));
        newButton.setText(text);
        return newButton;
    }
    
    public void setCustomLabelText(String input){
        customLabel.setText(input);
    }
    
    public void customInit(){
        stickButton.add(createNewButton("|||||||",0));
        jPanel1.add(stickButton.get(0));
    }
    
    public void resetButtonList(){
        stickButton.removeAll(stickButton);
    }
    
    public void addNewStickButton(String input,int index){
        stickButton.add(createNewButton(input,index));
    }
    
    public void updateUIStick(){
        clearPanel();
        stickButton.forEach(
            (n)->jPanel1.add(n)
        );
    }
    
    public void clearPanel(){
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    //end of MyFunction
    
    //listener adder
    public void addStickButtonListener(ActionListener al){
        stickButton.forEach((n)->n.addActionListener(al));
    }
    
    public void addResetButtonListener(ActionListener al){
        ResetBtn.addActionListener(al);
    }
    public void addMinMaxButtonListener(ActionListener al){
        minMaxBtn.addActionListener(al);
    }
    //end of listener adder
    
    
    /**
     * Creates new form BoardView
     */
    public BoardView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customLabel = new javax.swing.JLabel();
        ResetBtn = new javax.swing.JButton();
        minMaxBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 1, 10, 0));

        customLabel.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 24)); // NOI18N

        ResetBtn.setText("Reset");

        minMaxBtn.setText("MinMax");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(customLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minMaxBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResetBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(customLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ResetBtn)
                            .addComponent(minMaxBtn))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetBtn;
    private javax.swing.JLabel customLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minMaxBtn;
    // End of variables declaration//GEN-END:variables
}
